packages:
  - packages/*
onlyBuiltDependencies:
  - esbuild

# Catalog for standardizing dependency versions across workspace
catalog:
  # Core dependencies
  bpmn-js: ^13.2.2
  typescript: ^5.8.3

  # React ecosystem
  react: ^19.1.0
  react-dom: ^19.1.0

  # Type definitions
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@types/node": ^24.0.10
